-- Table creation & load (patients)
CREATE TABLE patients (
    Id TEXT, BIRTHDATE DATE, DEATHDATE DATE, SSN TEXT, DRIVERS TEXT,
    PASSPORT TEXT, PREFIX TEXT, FIRST TEXT, MIDDLE TEXT, LAST TEXT,
    SUFFIX TEXT, MAIDEN TEXT, MARITAL TEXT, RACE TEXT, ETHNICITY TEXT,
    GENDER TEXT, BIRTHPLACE TEXT, ADDRESS TEXT, CITY TEXT, STATE TEXT,
    COUNTY TEXT, FIPS TEXT, ZIP TEXT, LAT NUMERIC, LON NUMERIC,
    HEALTHCARE_EXPENSES NUMERIC, HEALTHCARE_COVERAGE NUMERIC, INCOME NUMERIC
);

CREATE TABLE conditions (
    START DATE, STOP DATE, PATIENT TEXT, ENCOUNTER TEXT,
    SYSTEM TEXT, CODE TEXT, DESCRIPTION TEXT
);

-- Cohort identification: breast cancer patients
-- SNOMED code 254837009 = "Malignant neoplasm of breast (disorder)"
-- Verified: 38 patients, no duplicate diagnoses (supports no-recurrence finding)
SELECT * FROM conditions WHERE code = '254837009';
